# site settings
title: Gagan
subtitle: Portfolio
email: gaganshtt7@gmail.com
description: I am an experienced data professional having worked mainly with data most of my career. My experience involves working mainly in extensive data wrangling and extraction from various sources, analysing data with multiple relevant statistical techniques to extract trends and insights, developing machine learning models for developing predictive insights from the data and reporting the data with advanced BI tools and graphing techniques. I also like to explore and apply advancements in technology related to data such as usage of GenAI to develop applications.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Reading
state: 
zip_code:
country: United Kingdom
phone: 07824061008

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/G7S-S
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/gagan-s-shetty/
  Twitter: 
  Facebook:
  Slack:
  Medium: https://gaganshetty.medium.com/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
