# site settings
title: Gagan
subtitle: Portfolio
email: gaganshtt7@gmail.com
description: A DETAILED SUMMARY OF THE VARIOUS PROJECT WORK THAT <br /> I HAVE CARRIED OUT AS PART OF MY ACADEMIA AND WORK.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Reading
state: 
zip_code:
country: United Kingdom
phone: 07824061008

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/G7S-S
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/gagan-s-shetty/
  Twitter: 
  Facebook:
  Slack:
  Medium: https://gaganshetty.medium.com/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
