# site settings
title: Gagan
subtitle: Portfolio
email: gaganshtt7@gmail.com
description: I am an experienced data professional with a strong background in data wrangling and extraction from various sources. My expertise includes analyzing data using a wide range of statistical techniques to extract meaningful trends and insights. Additionally, I have a proven track record in developing machine learning models to derive predictive insights from data and presenting the findings using advanced business intelligence tools and data visualization techniques. <br>I am also enthusiastic about exploring and applying cutting-edge data technologies, such as leveraging generative AI (GENAI), to develop innovative applications.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Reading
state: 
zip_code:
country: United Kingdom
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/G7S-S
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/gagan-s-shetty/
  Twitter: 
  Facebook:
  Slack:
  Medium: https://gaganshetty.medium.com/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
